name: demo_package_project

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1.0
        with:
          sdk: stable
      - name: Install dependencies
        run: dart pub get
      - name: Run VM tests
        run: dart test --platform vm

      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm install -g "@semantic-release/changelog"
      - run: npm install -g "@semantic-release/git"
      - run: npm install -g "pub-semantic-release"

      - name: Bump version
        run: |
          export NODE_PATH="$(npm root -g)"
          npx semantic-release@17
          ls -lah
          git status
          cat pubspec.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish to pub
        run: dart pub publish --dry-run

      - uses: sakebook/actions-flutter-pub-publisher@v1.3.1
        with:
          package_directory: ${{ matrix.package }}
          credential: ${{ secrets.PUB_CREDENTIALS }}
          flutter_package: true
          skip_test: true

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update pubspec and changelog
