name: demo_package_project

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sdk: [stable]
    steps:
      - uses: actions/checkout@v2
      - uses: cedx/setup-dart@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm install -g "@semantic-release/changelog"
      - run: npm install -g "@semantic-release/git"
      - run: npm install -g "pub-semantic-release"

      - name: Bump version
        run: |
          export NODE_PATH="$(npm root -g)"
          npx semantic-release@17
          ls -lah
          git status
          cat pubspec.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish to pub
        run: dart pub publish --dry-run

      - uses: sakebook/actions-flutter-pub-publisher@v1.3.1
        # if: steps.pubspec.outputs.changed == 0
        with:
          package_directory: ${{ matrix.package }}
          credential: ${{ secrets.PUB_CREDENTIALS }}
          flutter_package: true
          skip_test: true

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update pubspec and changelog
